SELECT substring('abcdef' FROM 2 FOR 3) AS substring_standard,
       substr('abcdef', -3, 2) AS substring_alias,
       length('Grüße') AS character_length,
       char_length('abc') AS character_length_alias,
       lower('AbC') AS lower_value,
       upper('AbC') AS upper_value,
       trim(BOTH 'x' FROM 'xxabcxx') AS trim_value,
       ltrim('xxabc', 'x') AS left_trim_value,
       rtrim('abcxx', 'x') AS right_trim_value,
       concat('a', NULL, 'b') AS concat_value,
       replace('abcabc', 'ab', 'x') AS replace_value,
       starts_with('abcdef', 'abc') AS starts_value,
       ends_with('abcdef', 'def') AS ends_value,
       contains('abcdef', 'cd') AS contains_value;
