(SELECT CAST('NaN' AS DOUBLE) AS value
 UNION ALL
 SELECT CAST('NaN' AS DOUBLE)
 UNION ALL
 SELECT CAST(1 AS DOUBLE))
INTERSECT ALL
(SELECT CAST('NaN' AS DOUBLE) AS value
 UNION ALL
 SELECT CAST(2 AS DOUBLE))
ORDER BY value;
