(SELECT CAST(1 AS SMALLINT) AS n
 UNION ALL
 SELECT CAST(2 AS BIGINT) AS other_name)
UNION ALL
(SELECT CAST(3 AS INTEGER) AS third_name
 UNION ALL
 SELECT CAST(NULL AS BIGINT) AS nullable_name)
ORDER BY n NULLS LAST;
